scam-django/scam_clone_django/games/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('gameTemplate/<game_id>', view=views.game, name='game'),
    path('submitReview/<game_id>', view=views.submitReview, name='submitReview'),
]

scam-django/scam_clone_django/pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home', view=views.home, name='home'),
    path('about', view=views.about, name='about'),
    path('search', view=views.search, name='search'),
    path('searchByCategory', view=views.searchByCategory, name='searchByCategory'),
]

scam-django/scam_clone_django/scam_clone_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include(('pages.urls' , 'pages'), namespace='pages')),
    path('games/', include('games.urls')),
    path('', include(('users.urls', 'home'), namespace='users')),
    path('checkout/', include(('checkout.urls','checkout'), namespace='checkout')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    
    
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

scam-django/scam_clone_django/templates/pages/about.html
<!DOCTYPE html>
{% extends 'pagesBase.html' %}
{% load static %}
{% block main %}
<html>
  <link rel="stylesheet" href="{% static 'css/about-stylesheet.css' %}?/v=1">
  <script src="{% static 'js/about-js.js' %}"></script>


    <body>
        
        <div class="container-fluid">
            <div id="dimmed_about_block" style="background: linear-gradient(rgba(0, 0, 0, 0.70), rgba(0, 0, 0, 0.70)), url({% static "ImageData/games2.jpg" %});">
                <img src="{% static "ImageData/games2.jpg" %}">
                <h1 class="titleFont">Access Games Instantly</h1>
                <p class="smallFont">
                    With nearly 30,000 games from AAA to indie and everything in-between. 
                    <br>
                    Enjoy exclusive deals, automatic game updates, and other great perks.
                </p>
            </div>
        </div>
            

            <div id="about_info_container" class="container">
              <div class="container aboutBlock">
                  <img class='slide-in-rtl' id="about_img1" src="https://cdn.cloudflare.steamstatic.com/store/about/cta_hero_community_pt3.png">
                    
                      <div class="fade-in">
                        <h1 class="titleFont">Join The Community</h1>
                        <p class="smallFont">
                            Meet new people, join groups, form clans, chat in-game and more!
                            <br>
                            With over 100 million potential friends (or enemies), the fun never stops.
                        </p>
                        
                      </div>
              </div>
              
              
              <div id='about_block2'>
                  <img id="about_img2" class="slide-in-ltr" src="https://cdn.cloudflare.steamstatic.com/store/about/cta_hero_hardware.png">
                  <div id="about_block2_text" class="fade-in"> 
                    <h1 class="titleFont">Experience Scam Hardware</h1>
                    <p class="smallFont">
                        We created the Scam Controller and the VR technologies that power the HTC Vive to making gaming on the PC even better.
                    </p>
                  </div>
              </div>
              
              <div class="container aboutBlock">
                  <img class='slide-in-rtl' id="about_img3" src="https://cdn.cloudflare.steamstatic.com/store/about/cta_hero_steamworks.png">
                  
                 <div class="fade-in">
                   <h1 class="titleFont">Release your Game</h1>
                   <p class="smallFont">
                       Scamworks is the set of tools and services that help <br> 
                       game developers and publishers <br>get the most out of distributing games on Scam.
                   </p>
                  
                 </div>
                 
              </div>
              <br>
            </div>
        
    </body>
    {% endblock main %}
</html>

scam-django/scam_clone_django/templates/pages/home.html
<!DOCTYPE html>
{% extends 'pagesBase.html' %}
{%load static%}
{%block main%}
<html>
  <link rel="stylesheet" href="{% static 'css/main-stylesheet.css' %}/?=v1">
  <script src="{% static 'js/main-js.js' %}"></script>

    <body>
        <div class="video-container" style="justify-content: center;">
            <video autoplay muted loop id="myVideo">
                <source src="{% static "ImageData/abstractbluebg_720.mp4" %}" type="video/mp4">
              </video>

            <div id="floating-nav" class="d-none d-md-block navbarCaption mx-auto">
                <nav class="navbar navbar-expand-sm navbarBg">
                    
                    <!-- Links -->
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link navBarItem" href="#" data-toggle="dropdown">
                            Your Store
                            </a>
                            <div class="dropdown-menu floating-nav-menu">
                              <a class="menuItem" href="#">Home</a>
                              <a class="menuItem" href="#">Community Recommendation</a>
                              <a class="menuItem" href="#">Recently Viewed</a>
                              <a class="menuItem" href="#">Scam Curators</a>
                            </div>
                          </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link navBarItem" href="#">New and Noteworthy</a>
                            <div class="dropdown-menu floating-nav-menu">
                              <a class="menuItem" href="#">Scam Replay 2022</a>
                              <a class="menuItem" href="#">Top Sellers</a>
                              <a class="menuItem" href="#">Most Played</a>
                              <a class="menuItem" href="#">Popular and Upcoming</a>
                          </li>

                        <li class="nav-item dropdown">
                          <a class="nav-link navBarItem" href="#">Categories</a>
        
                          <div class="dropdown-menu floating-nav-menu">
                            <a class="menuItem navBarItem" href="#">Action</a>
                            <a class="menuItem navBarItem" href="#">Roleplaying</a>
                            <a class="menuItem navBarItem" href="#">Strategy</a>
                            <a class="menuItem navBarItem" href="#">Adventure</a>
                            <a class="menuItem navBarItem" href="#">Sports</a>
                          </div>
                        </li>
                        
                        <li class="nav-item">
                          <a class="nav-link navBarItem" href="#">Labs</a>
                        </li>
                      </ul>

                      <form class="form-inline ml-auto" method='GET' action="{% url 'pages:search' %}">
                        
                        <input class="form-control" type="search" placeholder="Search" name="searched">
                        <button id="btn-search" class="btn" type="submit"><img  src="https://img.icons8.com/material-rounded/256/search.png">
                        </button>
                      </form>
                  </nav>
            </div>

            <div class="caption">
                <h5>Feb.06 - Feb.13 @10AM Pacific</h5>
                <img src="{% static "ImageData/nextfest.png" %}">
            </div>
        </div>

        <div id="main" class="container-fluid">
          <div class="sidebar d-none d-xl-block">
            <img src="https://steamstore-a.akamaihd.net/public/images//gift/steamcards_promo_02.png">
            <h5>GIFT CARDS</h5>
            <a href="#">Now Available on Scam</a>
            <h5>RECOMMENDED</h5>
            <a href="#">By Friends</a>
            <br>
            <a href="#">By Curators</a>
            <br>
            <a href="#">Tags</a>
            <br>
            <h5>DISCOVERY QUEUES</h5>
            <a href="#">Recommendations</a>
            <br>
            <a href="#">New Releases</a>
            <br>
            <h5>BROWSE CATEGORIES</h5>
            <a href="#">Top Sellers</a>
            <br>
            <a href="#">Recently Updated</a>
            <br>
            <a href="#">New Releases</a>
            <br>
            <a href="#">Upcoming</a>
            <br>
            <a href="#">Specials</a>
            <br>
            <a href="#">Virtual Reality</a>
            <br>
            <a href="#">Scam Controller Friendly</a>
            <h5>BROWSE BY GENRE</h5>
            <a href="#">Free to Play</a>
            <br>
            <a href="#">Early Access</a>
            <br>
            <a href="">Action</a>
            <br>
            <a href="#">Adventure</a>
            <br>
            <a href="#">Casual</a>
            <br>
            <a href="#">Indie</a>
            <br>
            <a href="#">Massively Multiplayer</a>
            <br>
            <a href="#">Racing</a>
            <h5>RECENTLY VIEWED</h5>
            <a href="#">Apex Legends</a>
            <br>
            <a href="#">CSGO</a>
            <br>
            <a href="#">Destiny: 2</a>
          </div>
          
        <div style=""
         id="demo" class="carousel slide carousel-fade" data-ride="carousel">

          <!-- Indicators -->
          <ul class="carousel-indicators">
            {% for game in games %}
                {% if forloop.first %}
            <li data-target="#demo" data-slide-to="0" class="active"></li>
                {% else %}
            <li data-target="#demo" data-slide-to="forloop.counter"></li>
                {% endif %}
            {% endfor %}
          </ul>
          
          <!-- The top slideshow -->
          <div class="carousel-inner">
            {% for game in games %}
            {% if forloop.first %}           
            <div class="carousel-item active">
            {% else %}
            <div class="carousel-item">
            {% endif %}
              <a href="{% url "game" game.id %}" >
                <img src="{{game.img_cover.url}}"> 
              </a>
            </div>
            {% endfor %}
          </div>
          
          <!-- Left and right controls -->
          <a class="carousel-control-prev" href="#demo" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
          </a>
          <a class="carousel-control-next" href="#demo" data-slide="next">
            <span class="carousel-control-next-icon"></span>
          </a>
        </div>
          <!-- End of top slideshow -->



        <div id="midTitle">
          <h2 class="midTitleFont">Trending this week</h2>
        </div>

        <div 
         id="demo2" class="carousel slide" data-ride="carousel">

          <!-- Indicators -->
          <ul class="carousel-indicators">
            <li data-target="#demo2" data-slide-to="0" class="active"></li>
            <li data-target="#demo2" data-slide-to="1"></li>
            <li data-target="#demo2" data-slide-to="2"></li>
          </ul>

          <!-- The bottom slideshow -->
          
          <div class="carousel-inner">
            <!--This Div Contains the full carousel item, with each div inside containing a single image with caption for each img-->
            <div class="carousel-item active">
            {% for game in games %}
              {% if forloop.counter < 4 %}
                <div class="carouselItem" style="background-image: url({{game.img_cover.url}});">
                
                <img class="carouselImg" src="{{game.img_cover.url}}">
              
                <a href="{% url 'game' game.id %}">
              <span class="carouselCaption">{{game.name}}<br> {{game.price}}$</span>
              </a>
            </div>
            {% endif %}
            {% endfor %}
          </div>
              
          <div class="carousel-item">
            {% for game in games %}
              {% if forloop.counter >= 4 and forloop.counter < 7 %}
                <div class="carouselItem" style="background-image: url({{game.img_cover.url}});">
                
                <img class="carouselImg" src="{{game.img_cover.url}}">
              
                <a href="{% url 'game' game.id %}">
              <span class="carouselCaption">{{game.name}}<br> {{game.price}}$</span>
              </a>
            </div>
            {% endif %}
            {% endfor %}
          </div>

          <div class="carousel-item">
            {% for game in games %}
              {% if forloop.counter >= 7 %}
                <div class="carouselItem" style="background-image: url({{game.img_cover.url}});">
                
                <img class="carouselImg" src="{{game.img_cover.url}}">
              
                <a href="{% url 'game' game.id %}">
              <span class="carouselCaption">{{game.name}}<br> {{game.price}}$</span>
              </a>
            </div>
            {% endif %}
            {% endfor %}
          </div>  
          </div>            
          
          <!-- Left and right controls -->
          <a class="carousel-control-prev" href="#demo2" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
          </a>
          <a class="carousel-control-next" href="#demo2" data-slide="next">
            <span class="carousel-control-next-icon"></span>
          </a>
        </div>
      </div>
    
    </body>

{% endblock main %}
</html>

scam-django/scam_clone_django/templates/pages/searchResult.html
{% extends 'productBase.html' %}
{% load static %}
{% block main %}
<html>
    <link rel="stylesheet" href="{% static "css/search-stylesheet.css" %}?/=v1">
    <script src= "{% static "js/main-js.js" %}"></script>

    

    <body>

        {% if games %}
    <div id='searchResults' class='container'>
            <form class="form" method='GET' action="{% url 'pages:searchByCategory' %}">
                <input class="form-control" type="search" placeholder="Search" name="searched">
                    <button id='searchButton' class="btn" type="submit"><img src="https://img.icons8.com/material-rounded/256/search.png">
                    </button>
                    <div id="categoryFilter">
                        <label class="smallFont" for="category">Filter by category</label>
                        <select name="category" id="categoryList">
                            <option disabled selected value></option>
                            {% for category in categories %}
                                <option class="smallFont" value="{{category}}">{{category}}</option>
                            {% endfor %}
                        </select>
                    </div>
              </form>
        
          
        {% for game in games %}
        <a href={% url 'game' game.id %}> 
            <div class="gameCard">
                    <img src="{{game.img_logo.url}}">
                    <span class="gameName">{{game.name}}</span>
                    <span>{{game.release_date}}</span>
                    <span class="gamePrice">{{game.price}}$</span>
                </div>
        </a>
        {% endfor %}
        
        {% else %}
            <center>
                <h1 id='notFound'>
                    Your search of {{searched}} returned no results.
                </h1>
            </center>
        {% endif %}
    </div>
    </body>
    {% endblock main %}
    </html>