scam-django/scam_clone_django/games/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('gameTemplate/<game_id>', view=views.game, name='game'),
    path('submitReview/<game_id>', view=views.submitReview, name='submitReview'),
]

scam-django/scam_clone_django/scam_clone_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include(('pages.urls' , 'pages'), namespace='pages')),
    path('games/', include('games.urls')),
    path('', include(('users.urls', 'home'), namespace='users')),
    path('checkout/', include(('checkout.urls','checkout'), namespace='checkout')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    
    
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

scam-django/scam_clone_django/users/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', view=views.login, name='login'),
    path('register', view=views.register, name='register'),
    path('logout', view=views.logout, name='logout'),
    path('activate/<uidb64>/<token>', view=views.activate, name='activate'),
    path('accountInfo', view=views.accountInfo, name='accountInfo'),
    path('confirmMailChange/<uidb64>/<token>/<newEmail>', view=views.confirmMailChange, name='confirmMailChange'),
    path('forgotPassword', view=views.forgotPassword, name='forgotPassword'),
    path('passwordReset/<uidb64>/<token>', view=views.passwordReset, name='passwordReset'),
]

scam-django/scam_clone_django/templates/forms/accountInfo.html
{% extends 'headerFooter.html' %}
{% load static %}
<html>
  {% block main %}

  <link rel="stylesheet" href="{% static 'css/accountInfo-stylesheet.css'%}/?=v1">
  <script src="{% static "js/accountInfo-js.js" %}"></script>
    

<body id="transparentBG" style="
 background: linear-gradient(rgba(0, 0, 0, 0.70), rgba(0, 0, 0, 0.70)), url({% static 'ImageData/cover.webp' %});">
 <div class="gradient-blur"></div>

 <div id="userInfoForm" class="container smallFont">
    <div class="container titleFont">
       Account Information
     </div>
    
     <div class="container smallFont">
        
       <div class="container">
        <label class="mediumFont" for="username"><b>Username: </b></label>
        <span class="smallFont">{{username}}</span>
        <button class="btn btn-primary">Change Username</button>
        <input id="nameInput" class="fade-in" type="text" placeholder="">
       </div>

        <div class="container">
            <label class="mediumFont" for="email"><b>Email: </b></label>
            <span class="smallFont">{{email}}</span>
            <button class="btn btn-primary" onclick="openForm(emailInput)">Change Email</button>
            
            <div id="emailInput" class="container">
              <form method="POST" class="fade-in">
                {% csrf_token %}
              <input class="fade-in" type="text" placeholder="Enter New Email" name="newEmail" required>
              <div class="btn-div">
                <button type="submit" name="emailSubmit">
                  <span style="color: whitesmoke;">Submit</span></button>
                </div>
              </form>
              
            </div>
             <br>
        </div>

         <div class="container">
            <label class="mediumFont" for="phone"><b>Phone: </b></label>
            <span class="smallFont">{{phone}}</span>
            <button class="btn btn-primary">Change Phone</button>
            <input id="phoneInput" class="fade-in" type="text" placeholder="">
             <br>
         </div>

          <div class="container smallFont">
            <label class="mediumFont" for="password"><b>Password: </b></label>
            <span class="smallFont">*****</span>
            <button class="btn btn-primary " onclick="openForm(passwordInput)">Change Password</button>
            
            <div id="passwordInput" class="container">
              <form method="POST" class="" style="">
                {% csrf_token %}
              <input class="" type="password" placeholder="Enter current password" name="currentPassword" required>
              
              <input class="" type="password" placeholder="Enter New password" name="newPassword" required>
              
              <div class="btn-div">
                <button type="submit" name="passwordSubmit">
                  <span style="color: whitesmoke;">Submit</span></button>
                </div>
                
              </form>
            </div>
            <p id="messages">
            {% if messages %}
              {% for message in messages %}
                    {{ message }}
                  {% endfor %}
                {% endif %}
            </p>
          </div>
           
       
    
     </div>
 </div>
</body>
  {% endblock main %}
</html>

scam-django/scam_clone_django/templates/forms/activateAccountMail.html
{% autoescape off %}
Hi, {{user.name}}
Thank you for signing up.

Please click on this link to activate your account:
http://{{domain}}{% url 'users:activate' uidb64=uid token=token %}

{% endautoescape %}

scam-django/scam_clone_django/templates/forms/forgotPassword.html
{% extends 'headerFooter.html'%}
{% load static %}
<html>
    {% block main %}
    <link rel="stylesheet" href="{% static 'css/forgot-password-stylesheet.css' %}/?=v1">

<body id="transparentBG" style="background: linear-gradient(rgba(0, 0, 0, 0.70), rgba(0, 0, 0, 0.70)), url({% static 'ImageData/cover.webp' %});">
 <div class="gradient-blur"></div>
 <div id="emailInputForm" class="container smallFont">
    <div class="container titleFont">
       <span>Enter your email</span>
     </div>
    
     <div class="container smallFont">
        
          <div class="container fade-in">
            <form method="POST" >
              {% csrf_token %}
            <input class="fade-in" type="text" placeholder="" name="email" required>

            <div id="btn-div">
              <button type="submit">
                <span>Submit</span></button>
              </div>
              
            </form>
            {% if messages %}
            {% for message in messages %}
                  {{ message }}
                {% endfor %}
              {% endif %}
          </div>
           
       
    
     </div>
 </div>
</body>
{% endblock main %}
</html>

scam-django/scam_clone_django/templates/forms/forgotPasswordMail.html
{% autoescape off %}
Hi, {{user.name}}
You've recieved this mail because you forgot Your Password.
Please click on this link to reset your password:
http://{{domain}}{% url 'users:passwordReset' uidb64=uid token=token %}

{% endautoescape %}

scam-django/scam_clone_django/templates/forms/login.html
<!DOCTYPE html>
{% extends 'headerFooter.html' %}
{%load static %}

<html>
  {% block main %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/login-stylesheet.css' %}/?v=1" >

  
    <body style="
    background: linear-gradient(rgba(0, 0, 0, 0.70), rgba(0, 0, 0, 0.70)), url({% static 'ImageData/cover.webp' %});">
        <div class="gradient-blur"></div>
        <img id="bg" src="{% static 'ImageData/games.jpg' %}">
  
        
        <form id="loginForm" method="POST" class="container smallFont fade-in">
          {% csrf_token %}
          <div>
            <label for="uname"><b>Sign in with account name</b></label>  
            <input type="text" placeholder="Enter Username" name="username" required>
        
            <label for="psw"><b>Password</b></label>
            <input type="password" placeholder="Enter Password" name="password" required>
            
            <div id="btn-div">
            <button type="submit">
              <span>Sign in</span></button>
              <p class = 'smallFont'>
                {% if messages %}
                  {% for message in messages %}
                    {{ message }}
                  {% endfor %}
                {% endif %}
                </p>
              <label class="smallFont"><a href="{% url 'users:register' %}">Not Registered?</a></label>
                <br>
              <label class="smallFont"><a href="{% url 'users:forgotPassword' %}">Forgot Password?</a></label>
            </div>

            
          </div>

        </form>
        <br>
    </body>
    
    {% endblock main %}
</html>

scam-django/scam_clone_django/templates/forms/mailChangeMail.html
{% autoescape off %}
Hi, {{user.name}}
You've recieved this mail because you requested a mail change.
Please click on this link to change your email address:
http://{{domain}}{% url 'users:confirmMailChange' uidb64=uid token=token newEmail=newEmail %}

{% endautoescape %}

scam-django/scam_clone_django/templates/forms/passwordReset.html
{% extends 'headerFooter.html' %}
{% load static %}
<html>
    {% block main %}
    <link rel="stylesheet" href="{% static 'css/password-reset-stylesheet.css' %}/?=v1">

    
<body style="background: linear-gradient(rgba(0, 0, 0, 0.70), rgba(0, 0, 0, 0.70)), url({% static 'ImageData/cover.webp' %});">
 <div class="gradient-blur"></div>
 <div id="forgotPasswordForm" class="container smallFont">
    <div class="container titleFont">
       <span>Create New Password</span>
     </div>
    
     <div class="container smallFont">
        
          <div class="container">
            <form id="passwordInput" method="POST" class="fade-in">
              {% csrf_token %}
            <input class="fade-in" type="password" placeholder="Enter New password" name="newPassword" required>
            <input class="fade-in" type="password" placeholder="Confirm New password" name="newPasswordConfirm" required>

            <div id='btn-div'>
              <button type="submit">
                <span>Submit</span></button>
              </div>
              
            </form>

          </div>
       
    
     </div>
 </div>
</body>
{% endblock main %}
</html>

scam-django/scam_clone_django/templates/forms/register.html
<!DOCTYPE html>
{% extends 'headerFooter.html' %}
{% load static %}
{%block main%}
<html>
        <link rel="stylesheet" href= "{% static "css/register-stylesheet.css" %}/?=v1">
        <script src="{% static 'js/register-js.js' %}"></script>

    
    <body style="background: linear-gradient(rgba(0, 0, 0, 0.70), rgba(0, 0, 0, 0.70)), url({% static 'ImageData/cover.webp' %});">
      <div class="gradient-blur">

      </div>

        <img id="bg" src="{% static 'ImageData/games.jpg' %}">
  
        
        <form id="registerForm" method="POST" class="container smallFont fade-in">
          {% csrf_token %}
          <div class="container titleFont">
            Create Your Account
          </div>
        
          <div class="container smallFont">
            <label for="username"><b>Username</b></label>
            <input type="text" placeholder="Enter Username" name="username" required>

            <label for="email"><b>Email</b></label>
            <input type="text" placeholder="Enter Email" name="email" required>

            <label for="phone"><b>Phone</b></label>
            <input type="text" placeholder="Enter Phone" name="phone" required>
        
            <label for="password"><b>Password</b></label>
            <input type="password" placeholder="Enter Password" name="password" required>
            
            <div style="text-align: center">
            <button type="submit">
              <span class='white'>Sign Up</span></button>
            </div>

            {% if form.errors %}
            <p class = "smallFont white">
              Registration Failed
            </p>
          {% endif %}
          </div>
      

          
          
        </form>

    </body>
    <br>
    
    {% endblock main %}
</html>