scam-django/scam_clone_django/checkout/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('checkout/<game_id>', view=views.checkout, name='checkout'),
    path('paymentSuccess/<game_id>', view=views.paymentSuccess, name='paymentSuccess'),
    path('paymentFailed/<game_id>', view=views.paymentFailed, name='paymentFailed')
]

scam-django/scam_clone_django/games/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('gameTemplate/<game_id>', view=views.game, name='game'),
    path('submitReview/<game_id>', view=views.submitReview, name='submitReview'),
]

scam-django/scam_clone_django/scam_clone_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include(('pages.urls' , 'pages'), namespace='pages')),
    path('games/', include('games.urls')),
    path('', include(('users.urls', 'home'), namespace='users')),
    path('checkout/', include(('checkout.urls','checkout'), namespace='checkout')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    
    
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

scam-django/scam_clone_django/games/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as lazy
from users.models import User
from django.utils import timezone
# Create your models here.

def sysreqCheck(requirements : str):
    specs = ["Processor" , "Memory", "OS", "Graphics", "DirectX", "Storage"]
    for spec in specs:
        if requirements.__contains__(spec) == False:
            raise ValidationError(lazy("Missing requirement: " + spec))

def defaultDict():
    return dict()

class Publisher(models.Model):
    name = models.CharField(max_length=50)
    gameCount = models.IntegerField() 
    email = models.EmailField(verbose_name="Contact Email")
    
    def __str__(self) -> str:
        return self.name

class Games(models.Model):
    #gameID = models.AutoField(verbose_name= "ID")
    name = models.CharField(max_length=50)
    category = models.CharField(max_length=50)
    release_date = models.DateField(auto_now_add=True)
    description = models.TextField(blank=True)
    requirements = models.TextField(validators=[sysreqCheck])
    price = models.FloatField()
    img_logo = models.ImageField(verbose_name='Logo Image', upload_to='photos/%y/%m/%d',height_field=None, width_field=None, max_length=None, null=True, blank=True)
    img_cover = models.ImageField(verbose_name='Splash Art',upload_to='photos/%y/%m/%d', height_field=None, width_field=None, max_length=None, default=None, null=True, blank=True)
    img_1 = models.ImageField(verbose_name='Trailer Image 1',upload_to='photos/%y/%m/%d', height_field=None, width_field=None, max_length=None, default=None, null=True, blank=True)
    img_2 = models.ImageField(verbose_name='Trailer Image 2',upload_to='photos/%y/%m/%d', height_field=None, width_field=None, max_length=None, default=None, null=True, blank=True)
    img_3 = models.ImageField(verbose_name='Trailer Image 3',upload_to='photos/%y/%m/%d', height_field=None, width_field=None, max_length=None, default=None, null=True, blank=True)
    trailer = models.FileField(verbose_name='Video Trailer',upload_to='videos/%y/%m/%d', blank=True, null=True)
    developerName = models.CharField(max_length=50)
    publisherName = models.ForeignKey(to=Publisher, on_delete=models.DO_NOTHING)
    
    def __str__(self) -> str:
        return self.name

class Review(models.Model):
    game = models.ForeignKey(Games, on_delete=models.DO_NOTHING)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    verdict = models.IntegerField(verbose_name="Recommended?", default=-1)
    review = models.TextField(verbose_name="Review")
    review_date = models.DateTimeField(default=timezone.now)

    

scam-django/scam_clone_django/games/views.py
from django.shortcuts import render
from .models import Games, Review
from checkout.models import Order
from django.http import HttpResponse
from django.utils import timezone
# Create your views here.

def game(request, game_id):
    req_game = Games.objects.get(pk=game_id)
    current_reviews = req_game.review_set.all()
    current_user_review = req_game.review_set.filter(user= request.user)
    if Order.objects.filter(user_id = request.user, game = req_game).exists():
        isOwned = True
    else:
        isOwned = False
    return render(request, 'games/gameTemplate.html', context= {"game" : req_game, "reviews" : current_reviews, "user_review": current_user_review, "isOwned": isOwned})

def submitReview(request, game_id):
    if request.method == "GET":
        user = request.user
        game = Games.objects.get(pk=game_id)
        
        hasReviewed = False if not Review.objects.filter(user=user, game=game).values() else True
        if hasReviewed:
            return updateReview(request, game_id)
        
        user_review = request.GET.get('review')
        isRecommended = 1 if request.GET.get('isRecommended') == 'on' else 0
        review = Review(user=user, game=game, verdict=isRecommended, review=user_review)
        review.save()
    
    current_reviews = game.review_set.all()
    new_user_review = game.review_set.filter(user= request.user)
    return render(request, 'games/gameTemplate.html', context= {"game" : game, "reviews": current_reviews, "user_review": new_user_review})

def updateReview(request, game_id):
    if request.method == 'GET':
        user = request.user
        game = Games.objects.get(pk=game_id)
        old_review = Review.objects.get(user=user, game=game)
        
        new_review = request.GET.get('review')
        new_verdict = 1 if request.GET.get('isRecommended') == 'on' else 0

        old_review.review = new_review
        old_review.verdict = new_verdict
        old_review.review_date = timezone.now()
        old_review.save()
        
    current_reviews = game.review_set.all()
    new_user_review = game.review_set.filter(user= request.user)
    return render(request, 'games/gameTemplate.html', context= {"game" : game, "reviews": current_reviews, "user_review": new_user_review})
            

scam-django/scam_clone_django/templates/games/gameTemplate.html
<!DOCTYPE html>
{% extends 'productBase.html' %}
{% load static %}
{% block main %}
<html>
  <link rel="stylesheet" href="{% static 'css/product-stylesheet.css' %}">
  <script src="{% static 'js/product-js.js' %}"></script>
  
    <body>
        
            <!--Game Highlights Container-->
            <div id="game-highlight-div" class="container">
                <div id="demo" class="carousel slide carousel-fade vid-carousel" data-ride="carousel" data-interval="false">

          <!-- Indicators -->
          <ul class="carousel-indicators">
            <li data-target="#demo" data-slide-to="0" class="active" style="background-image: url({{game.img_cover.url}});"></li>
            <li data-target="#demo" data-slide-to="1" style="background-image: url({{game.img_1.url}});"></li>
            <li data-target="#demo" data-slide-to="2" style="background-image: url({{game.img_2.url}});"></li>
            <li data-target="#demo" data-slide-to="3" style="background-image: url({{game.img_3.url}});"></li>
          </ul>
          
          <!-- The slideshow -->
          <div class="carousel-inner">
            <div class="carousel-item active">
                <video controls autoplay muted id="myVideo" width="100%" height="100%">
                    <source src="{{game.trailer.url}}" type="video/mp4">
                  </video>
            </div>
            <div class="carousel-item">
              <img src="{{game.img_1.url}}">
            </div>
            <div class="carousel-item">
              <img src="{{game.img_2.url}}">
            </div>
            <div class="carousel-item">
                <img src="{{game.img_3.url}}">
              </div>
          </div>
          
          <!-- Left and right controls -->
          <a class="carousel-control-prev" href="#demo" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
          </a>
          <a class="carousel-control-next" href="#demo" data-slide="next">
            <span class="carousel-control-next-icon"></span>
          </a>
        </div>

        <div id="game-highlight">
            <img class="game_header_image_full" src="{{game.img_cover.url}}">
            <p class="smallFont">
                {{game.description}}
                <br> 
                <p class="tinyFont">
                    RELEASE DATE: &#160; &#160; &#160; &#160; &#160; &#160;
                    {{game.release_date}}
                    <br>
                    DEVELOPER: &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; 
                    {{game.developerName}}
                    <br>
                    PUBLISHER: &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160;&#160;
                    {{game.publisherName}}
                </p>
            </p>
        </div>

                
        </div>

        <div class="container" id="game-price">
            <div class="smallFont">
                Purchase {{game.name}}
            </div>
            

            <div id="price">
              {% if isOwned is True %}
                <p class='review-verdict'>You already own the game</p>
                {% else %}
                    <span>${{game.price}} USD</span>

                <div id="btn-buy">
                  <a href="{% url 'checkout:checkout' game.id %}">
                    <button type="button" class="btn-success"><span>Buy Game</span></button>
                  </a>
                </div>
                {% endif %}
            </div>
            
          </div>

        <div class='container' id="sysreq">
          <span class="smallFont">
            System Requirements &#160; &#160;
          </span>
          <br>
          <div id="req-type" class="smallFont">
            {{game.requirements | linebreaksbr}}
          </div>
        </div>
        <br>
        
        
        {% if user_review %}
        <div class='container' style="display: block;">
          <h4 class='review-label'>
            Your review of {{game.name}}:
          </h4>
        </div>

         <div id='user-review' class='container review-container'>
            {% for review in user_review %}
            <p>
              <span class="review-username">{{review.user}}</span>
            <span class="review-date">Posted: {{review.review_date}}</span></p>
              
            <p class="review-verdict">
            {% if review.verdict == 1 %}
                <img src={% static 'ImageData/thumbs_up.png'%}>
                Recommended</p>
              {% else %}
              <img src={% static 'ImageData/thumbs_down.png'%}>
              Not Recommended</p>
              {% endif %}
              <p style="color:whitesmoke">{{review.review}}</p>
            
            <button type="button" class='btn-primary' onclick="showUpdateReview()">
              Update Review
            </button>
         </div>

         <form id='update-review' class='container review-container' method="GET" action="{% url 'submitReview' game.id %}">
            <textarea class="review-textarea" type='text' name='review' rows="4" cols="50">{{review.review}}</textarea>
            <br>

            {% if review.verdict == 1 %}
            <input type='checkbox' name='isRecommended' id='isRecommended' checked>
            {% else %}
            <input type='checkbox' name='isRecommended' id='isRecommended'>
            {% endif %}

            <label class="review-verdict" for="isRecommended">Recommended?</label>
            <br>
            <button type="submit" class='btn-primary'><span>Submit</span></button>
          </form>
          {% endfor %}
         <br> 

        {% else %}
        {% if isOwned is True %}
        <form class='container review-container' method="GET" action="{% url 'submitReview' game.id %}">
            <label class="review-label" for="review">Leave a review of the game</label>
            <br>
            <textarea class="review-textarea" type='text' name='review'rows="4" cols="50"></textarea>
            <br>
            <input type='checkbox' name='isRecommended' id='isRecommended'>
            <label class='review-verdict' for="isRecommended">Recommended?</label>
            <br>
            <button type="submit" class='btn-primary'><span>Submit Review</span></button>
        </form>
        <br>
        {% else %}
        <div style='text-align: center'>
          <h3 class="container review-label">Please purchase the game to leave a review.</h3>
          <br>
        </div>
        {% endif %}


      {% endif %}


        <div class="container">
          <h3 class='review-label'>Player's Reviews of {{game.name}}:</h3>
        </div>
        <div class="container review-container">
          
          {% for review in reviews %}
            {% if review.user != user %}
            <p>
              <span class="review-username">{{review.user}}</span>
            <span class='review-date'>Posted: {{review.review_date}}</span></p>
              
            <p class='review-verdict'>
            {% if review.verdict == 1 %}
                <img src={% static 'ImageData/thumbs_up.png'%}>
                Recommended</p>
              {% else %}
              <img src={% static 'ImageData/thumbs_down.png'%}>
              Not Recommended</p>
              {% endif %}
              <p class='review-verdict'>{{review.review}}</p>
            {% endif %}
          {% endfor %}
        </div>
        

    </body>
    {% endblock main %}
    
</html>