scam-django/scam_clone_django/games/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('gameTemplate/<game_id>', view=views.game, name='game'),
    path('submitReview/<game_id>', view=views.submitReview, name='submitReview'),
]

scam-django/scam_clone_django/pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home', view=views.home, name='home'),
    path('about', view=views.about, name='about'),
    path('search', view=views.search, name='search'),
    path('searchByCategory', view=views.searchByCategory, name='searchByCategory'),
]

scam-django/scam_clone_django/scam_clone_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include(('pages.urls' , 'pages'), namespace='pages')),
    path('games/', include('games.urls')),
    path('', include(('users.urls', 'home'), namespace='users')),
    path('checkout/', include(('checkout.urls','checkout'), namespace='checkout')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    
    
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

scam-django/scam_clone_django/users/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', view=views.login, name='login'),
    path('register', view=views.register, name='register'),
    path('logout', view=views.logout, name='logout'),
    path('activate/<uidb64>/<token>', view=views.activate, name='activate'),
    path('accountInfo', view=views.accountInfo, name='accountInfo'),
    path('confirmMailChange/<uidb64>/<token>/<newEmail>', view=views.confirmMailChange, name='confirmMailChange'),
    path('forgotPassword', view=views.forgotPassword, name='forgotPassword'),
    path('passwordReset/<uidb64>/<token>', view=views.passwordReset, name='passwordReset'),
]

scam-django/scam_clone_django/templates/headerFooter.html
{% load static %}

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

<nav class="d-flex navbar navbar-expand-md darkNav navbar-dark">
            
    <div class="mx-auto bg">
        <a href="{% url 'pages:home' %}"><img
            class="logoBig" src="https://store.cloudflare.steamstatic.com/public/shared/images/header/logo_steam.svg?t=962016"></a>            
    </div>

    <button type="button" class="d-none d-md-block btn btn-success" data-target="#">
        <img width="15px" height="15px" src="https://img.icons8.com/material-sharp/256/download--v1.png">Install Scam</button>

      </nav>
</head>

{% block main %}
    
{% endblock main %}



<div class="card-footer" style="background-color: #171a21; width: 100%; height:100px; padding: 20px 350px; color: whitesmoke;
    overflow: hidden; position: fixed; bottom: 0px; text-align:center"  >
      <div style="float: left; padding-right: 10px; height: 100%;">
        <img  src="https://store.cloudflare.steamstatic.com/public/images/footerLogo_valve_new.png" width="88px" height="25px" alt="Valve Software">
      </div>
      <div style="float: right; padding-left: 10px; height: 100%;">
        <img  src="https://store.cloudflare.steamstatic.com/public/images/v6/logo_steam_footer.png" alt="Valve Software" width="92px" height="26px">
      </div>
    <span>
      Made with love by: Nhom7 © 2024
    </span>
    </div>
</html>

scam-django/scam_clone_django/templates/pagesBase.html
{%load static%}

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
        <script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
        
        <nav class="d-flex navbar navbar-expand-md darkNav navbar-dark">
            <!-- Toggler/collapsibe Button -->
            <span class="d-md-none d-block" style="cursor:pointer" onclick="openNav()"><img width="30px" height="30px" src="https://icon-library.com/images/hamburger-menu-icon-png-white/hamburger-menu-icon-png-white-10.jpg"></span>

            <div id="myNav" class="overlay">
              <a href="javascript:void(0)" class="closebtn" onclick="closeNav()"><img width="30px" height="30px" src="https://icon-library.com/images/hamburger-menu-icon-png-white/hamburger-menu-icon-png-white-10.jpg"></a>
              <div class="overlay-content">
                <ul class="navbar-nav pl-4 pt-1">
                  <li class="nav-item dropdown">
                      <a class="nav-link" href="#" data-toggle="dropdown">
                        Store
                      </a>
                      <div style="background-color: #171a21; z-index: -10" class="dropdown-menu">
                        <a class="menuItem" href={% url 'pages:home' %}>Home</a>
                        <a class="menuItem" href="#">Discovery Queue</a>
                        <a class="menuItem" href="#">Wishlist</a>
                        <a class="menuItem" href="#">Points Shop</a>
                        <a class="menuItem" href="#">News</a>
                        <a class="menuItem" href="#">Stats</a>
                      </div>
                    </li>
                  <li class="nav-item">
                      <a class="nav-link" href="#">Support</a>
                    </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link" href="#">Account</a>
  
                    <div style="background-color: #171a21;" class="dropdown-menu">
                      {% if user.is_authenticated %}
                        <a class="menuItem" href="{% url 'users:logout' %}">Logout</a>
                        <a class="menuItem" href="{% url 'users:accountInfo'%}">Account Settings</a>
                      {% else %}
                        <a class="menuItem" href="{% url 'users:login' %}">Login</a>
                        <a class="menuItem" href="{% url 'users:register'%}">Sign Up</a>
                      {% endif%}
                      
                    </div>
                  </li>
                  
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'pages:about' %}">About</a>
                  </li>
                </ul>
              </div>
            </div>
            
        <div class="mx-auto bg">
            <a class="float-left" href={% url 'pages:home'%}><img
                class="logoBig" src="https://store.cloudflare.steamstatic.com/public/shared/images/header/logo_steam.svg?t=962016"></a>
            
            <!-- Navbar links -->
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
              <ul class="navbar-nav pt-1" >
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" data-toggle="dropdown">
                      Store
                    </a>
                    <div style="background-color: #171a21; z-index: -1;" class="dropdown-menu">
                      <a class="menuItem" href="#">Home</a>
                      <a class="menuItem" href="#">Discovery Queue</a>
                      <a class="menuItem" href="#">Wishlist</a>
                      <a class="menuItem" href="#">Points Shop</a>
                      <a class="menuItem" href="#">News</a>
                      <a class="menuItem" href="#">Stats</a>
                    </div>
                  </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Support</a>
                  </li>
                  
                <li class="nav-item dropdown">
                  <a class="nav-link" href="#">Account</a>
                  <div style="background-color: #171a21; z-index:-1;" class="dropdown-menu">
                    {% if user.is_authenticated %}
                      <a class="menuItem" href="{% url 'users:logout' %}">Logout</a>
                      <a class="menuItem" href="{% url 'users:accountInfo'%}">Account Settings</a>
                    {% else %}
                      <a class="menuItem" href="{% url 'users:login' %}">Login</a>
                      <a class="menuItem" href="{% url 'users:register'%}">Sign Up</a>
                    {% endif %}
                  </div>
                </li>
                
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'pages:about' %}">About</a>
                </li>

                
                <li class="nav-item">
                  
                  <p class='menuItem' style='margin: 0px'>
                    {% if user.is_authenticated %}
                    Welcome, {{user.name}}. 
                    {% else %}
                    Welcome, Guest.
                    {% endif %}
                  </p>
                  
                  
                </li>
                
              </ul>
            </div>
        </div>

        <button type="button" class="d-none d-md-block btn btn-success" data-target="#">
            <img width="15px" height="15px" src="https://img.icons8.com/material-sharp/256/download--v1.png">Install Scam</button>

          </nav>
    </head>

    
    {%block main%}

    {% endblock main %}


    <div class="card-footer" style="background-color: #171a21; width: 100%; height:100px; padding: 20px 350px; color: whitesmoke;
    overflow: hidden; position: relative; bottom: 0px; text-align:center"  >
      <div style="float: left; padding-right: 10px; height: 100%;">
        <img  src="https://store.cloudflare.steamstatic.com/public/images/footerLogo_valve_new.png" width="88px" height="25px" alt="Valve Software">
      </div>
      <div style="float: right; padding-left: 10px; height: 100%;">
        <img  src="https://store.cloudflare.steamstatic.com/public/images/v6/logo_steam_footer.png" alt="Valve Software" width="92px" height="26px">
      </div>
    <span>
      Made with love by: Nhom7 © 2024
    </span>
    </div>
</html>

scam-django/scam_clone_django/templates/productBase.html
{%load static%}

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
        <script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
        
        
        
        <nav class="d-flex navbar navbar-expand-md darkNav navbar-dark">
            <!-- Toggler/collapsibe Button -->
            <span class="d-md-none d-block" style="cursor:pointer" onclick="openNav()"><img width="30px" height="30px" src="https://icon-library.com/images/hamburger-menu-icon-png-white/hamburger-menu-icon-png-white-10.jpg"></span>

            <div id="myNav" class="overlay">
              <a href="javascript:void(0)" class="closebtn" onclick="closeNav()"><img width="30px" height="30px" src="https://icon-library.com/images/hamburger-menu-icon-png-white/hamburger-menu-icon-png-white-10.jpg"></a>
              <div class="overlay-content">
                <ul class="navbar-nav pl-4 pt-1">
                  <li class="nav-item dropdown">
                      <a class="nav-link" href="#" data-toggle="dropdown">
                        Store
                      </a>
                      <div style="background-color: #171a21;" class="dropdown-menu">
                        <a class="menuItem" href="{% url 'pages:home' %}">Home</a>
                        <a class="menuItem" href="#">Discovery Queue</a>
                        <a class="menuItem" href="#">Wishlist</a>
                        <a class="menuItem" href="#">Points Shop</a>
                        <a class="menuItem" href="#">News</a>
                        <a class="menuItem" href="#">Stats</a>
                      </div>
                    </li>
                  <li class="nav-item">
                      <a class="nav-link" href="#">Support</a>
                    </li>
                    <li class="nav-item dropdown">
                      <a class="nav-link" href="#">Account</a>
                      <div style="background-color: #171a21;" class="dropdown-menu">
                        {% if user.is_authenticated %}
                          <a class="menuItem" href="{% url 'users:logout' %}">Logout</a>
                          <a class="menuItem" href="{% url 'users:accountInfo'%}">Account Settings</a>
                        {% else %}
                          <a class="menuItem" href="{% url 'users:login' %}">Login</a>
                          <a class="menuItem" href="{% url 'users:register'%}">Sign Up</a>
                        {% endif %}
                      </div>
                    </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'pages:about' %}">About</a>
                  </li>

                  <li class="nav-item">
                    <p class='menuItem' style='margin: 0px'>
                      {% if user.is_authenticated %}
                      Welcome, {{user.name}}. 
                      {% else %}
                      Welcome, Guest.
                      {% endif %}
                    </p>
                  </li>
                </ul>
              </div>
            </div>
            
        <div class="mx-auto bg">
            <a class="float-left" href="{% url 'pages:home' %}"><img
                class="logoBig" src="https://store.cloudflare.steamstatic.com/public/shared/images/header/logo_steam.svg?t=962016"></a>
            
            <!-- Navbar links -->
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
              <ul class="navbar-nav pt-1">
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" data-toggle="dropdown">
                      Store
                    </a>
                    <div style="background-color: #171a21;" class="dropdown-menu">
                      <a class="menuItem" href="#">Home</a>
                      <a class="menuItem" href="#">Discovery Queue</a>
                      <a class="menuItem" href="#">Wishlist</a>
                      <a class="menuItem" href="#">Points Shop</a>
                      <a class="menuItem" href="#">News</a>
                      <a class="menuItem" href="#">Stats</a>
                    </div>
                  </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Support</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link" href="#">Account</a>
                    <div style="background-color: #171a21;" class="dropdown-menu">
                      {% if user.is_authenticated %}
                        <a class="menuItem" href="{% url 'users:logout' %}">Logout</a>
                        <a class="menuItem" href="{% url 'users:accountInfo'%}">Account Settings</a>
                      {% else %}
                        <a class="menuItem" href="{% url 'users:login' %}">Login</a>
                        <a class="menuItem" href="{% url 'users:register'%}">Sign Up</a>
                      {% endif %}
                    </div>
                  </li>
                
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'pages:about' %}">About</a>
                </li>

                <li class="nav-item">
                  <p class='menuItem' style='margin: 0px'>
                    {% if user.is_authenticated %}
                    Welcome, {{user.name}}. 
                    {% else %}
                    Welcome, Guest.
                    {% endif %}
                  </p>
                </li>

              </ul>
            </div>
        </div>

        <button type="button" class="d-none d-md-block btn btn-success" data-target="#">
            <img width="15px" height="15px" src="https://img.icons8.com/material-sharp/256/download--v1.png">Install Scam</button>

          </nav>
    </head>

    
    {%block main%}

    {% endblock main %}


    <footer class="page-footer">
    <div class="card-footer" style="background-color: #171a21; width: 100%; height:100px; padding: 20px 350px; color: whitesmoke;
    overflow: hidden; position: fixed; bottom: 0px; text-align:center"  >
      <div style="float: left; padding-right: 10px; height: 100%;">
        <img  src="https://store.cloudflare.steamstatic.com/public/images/footerLogo_valve_new.png" width="88px" height="25px" alt="Valve Software">
      </div>
      <div style="float: right; padding-left: 10px; height: 100%;">
        <img  src="https://store.cloudflare.steamstatic.com/public/images/v6/logo_steam_footer.png" alt="Valve Software" width="92px" height="26px">
      </div>
    <span>
      Made with love by: Nhom7 © 2024
    </span>
    </div>
  </footer>
</html>